version: '3.8'
services:

  # Django application
  app:
    build: .
    volumes:
      - ./:/app:rw
    ports:
      - 5000:5000
    command: flask run -h0.0.0.0 -p5000
    depends_on:
      - database
    environment:
      FLASK_ENV: development

  # Main database
  database:
    image: postgres:13-alpine
    volumes:
      - ./.local/database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
